import "./globals.css";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Russo_One } from "next/font/google";

const kalam = Russo_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-kalam",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
